### PR TITLE
Add idrall dep to Inigo.toml

### PR DESCRIPTION
**Pull request by alexhumphreys**
This adds Idrall as an `extra-dep`. Running `inigo fetch-deps prod` will successfully pull it.

I wasn't able to get `inigo build-deps` to run because of a circular dependency with the `Markdown`, `SemVer` and `Toml` modules. This could be a bug in how circular dependencies are calculated, since they all just depend on `Extra` or `Fmt`, neither of which have any dependencies. But fixing that can be future work.

Other strange thing was that `sub-dirs` needs that `""` element, otherwise it just silently fails to pull the dependency.

I'll rebase this after #27 is merged to make sure I didn't break CI.

### CODE REVIEW

**Comment by Z-snails** [comment]
I fixed the circular dependency with #29. However, there's now a different error because the packages on inigo.pm are a bit old and outdated, because I don't have the login for the Base namespace.

**Comment by alexhumphreys** [comment]
Oh damn, thanks for fixing that decency issue!

And ouch, that Base issue sounds a little less fixable. I'm a bit worried about the whole namespace/registry/upload/website side of inigo. Guess it was set up by @hayesgm, but I think he deleted his original inigo, so it seems he's out of the project. That leaves none of us with admin privileges for maintaining it.

@Z-snails you have any thoughts on this?

**Comment by Z-snails** [comment]
My immediate plan was to just use extra-deps for everything 😅

Another idea I've had is some sort of resolver (probably hosted on a git repo) which maps regular deps to extra-deps (or something else). A bit like stack snapshots. Although I don't know if I'll get round to that any time soon.

**Comment by alexhumphreys** [comment]
Haha I was thinking the same thing, extra-deps for everything then maybe look into package sets as a long term solution (at least I think that's what you meant, I don't know much about stack 😅)

Not sure how much work a package set is, but there is some prior art here at least https://github.com/shmish111/smoke-hill

**Comment by Z-snails** [comment]
Yep, that's the idea!

**Pull request merged**
