### PR TITLE
Mark instances as covering

### PR DESCRIPTION
**Pull request by claymager**
Prelude now sets Eq and Show to be total by default, so we need to mark them as covering in order to build.

### CODE REVIEW

**Comment by Z-snails** [comment]
Thanks for this!
Could you update the idris2 submodule to latest please?

**Comment by claymager** [comment]
I think I did that right? I haven't actually used submodules before.

**Comment by claymager** [comment]
Ah. See idris-lang/idris2#2134

**Comment by Z-snails** [comment]
`Inigo.ipkg` is generated, you should change `Inigo.dhall` instead. Ideally that file should be added to `.gitignore`.

**Pull request merged**
